### ISSUE TITLE
Concurrency issues in %poll

### ISSUE THREAD

**Issue by fungional** [oneiricsky/alice#3]
# Current Situation

When two polls are triggered such that they are both active at the same time, anyone who votes via `%choose <n>`  will vote in both polls at once.

# Change

Add some kind of locking (perhaps a mutex?) around the `%poll` logic to prevent multiple polls from occurring at the same time.

**Comment by oneiricsky** [comment]
Poll was removed until I feel like writing it. Furthermore, a collector *should* work like with this like google and image since message collector is a thing.
