### ISSUE TITLE
Possible concurrency issues in utils/reaction_tracking

### ISSUE THREAD

**Issue by fungional** [oneiricsky/alice#6]
Some of the code in `utils/reaction_tracking.js` handles storing some tracking information in the record store. This record store is mutated without any forms of locking, and this environment is concurrent, so there could be race conditions involved in this recording tracking information.

Investigate whether concurrency bugs are possible. If they are, consider adding a lock of some sort (since #3 needs locking too, this shouldn't be much of a hassle).

**Comment by oneiricsky** [comment]
Locking isn't relevant as of now. Will reopen should this be relevant again.
